src/Entity/User.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ApiResource(
 *      collectionOperations={"get"},
 *      itemOperations={"get", "put"}
 * )
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="`user`")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="datetime")
     */
    private $join_date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\OneToMany(targetEntity=Account::class, mappedBy="user_id")
     */
    private $accounts;

    /**
     * @ORM\OneToMany(targetEntity=Post::class, mappedBy="author")
     */
    private $posts;

    public function __construct()
    {
        $this->accounts = new ArrayCollection();
        $this->posts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_RESTRICTED
        $roles[] = 'ROLE_RESTRICTED';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getJoinDate(): ?\DateTimeInterface
    {
        return $this->join_date;
    }

    public function setJoinDate(\DateTimeInterface $join_date): self
    {
        $this->join_date = $join_date;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection|Account[]
     */
    public function getAccounts(): Collection
    {
        return $this->accounts;
    }

    public function addAccount(Account $account): self
    {
        if (!$this->accounts->contains($account)) {
            $this->accounts[] = $account;
            $account->setUserId($this);
        }

        return $this;
    }

    public function removeAccount(Account $account): self
    {
        if ($this->accounts->removeElement($account)) {
            // set the owning side to null (unless already changed)
            if ($account->getUserId() === $this) {
                $account->setUserId(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Post[]
     */
    public function getPosts(): Collection
    {
        return $this->posts;
    }

    public function addPost(Post $post): self
    {
        if (!$this->posts->contains($post)) {
            $this->posts[] = $post;
            $post->setAuthor($this);
        }

        return $this;
    }

    public function removePost(Post $post): self
    {
        if ($this->posts->removeElement($post)) {
            // set the owning side to null (unless already changed)
            if ($post->getAuthor() === $this) {
                $post->setAuthor(null);
            }
        }

        return $this;
    }
}

templates/addpost.html.twig
<!DOCTYPE html>
<head>
    <link rel="stylesheet" type="text/css" href="{{ asset('css/header-nav-style.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('css/post-style.css') }}">
    <script src="{{ asset('https://kit.fontawesome.com/3d9e005fd2.js') }}" crossorigin="anonymous"></script>
    <title>Twarzobaza</title>
</head>
<body>
    <div class="main-container">
        {{ include('header_nav.html.twig') }}
        <main>
            {{ form_start(form, {'method': 'POST', 'attr': {'class': 'post-form'}}) }}
                {{ form_widget(form.title, {'attr': {'class': 'title-input'}}) }}
                {{ form_widget(form.content, {'attr': {'class': 'content-textarea'}}) }}
                {{ form_widget(form.addpost, {'attr': {'class': 'submit-button'}}) }}
            {{ form_end(form, {'render_rest': false}) }}
        </main>
    </div>
</body>

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {# Run `composer require symfony/webpack-encore-bundle`
           and uncomment the following Encore helpers to start using Symfony UX #}
        {% block stylesheets %}
            {#{{ encore_entry_link_tags('app') }}#}
        {% endblock %}

        {% block javascripts %}
            {#{{ encore_entry_script_tags('app') }}#}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/change_password.html.twig
<!DOCTYPE html>
<head>
    <link rel="stylesheet" type="text/css" href="{{ asset('css/header-nav-style.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('css/change-password-style.css') }}">
    <script type="text/javascript" src="{{ asset('js/password-validation.js') }}" defer></script> 
    <title>Twarzobaza - Zmień hasło</title>
</head>
<body>
    <div class="main-container">
        <header>
            <h1><a href="home">twarzobaza</a></h1>
        </header>
        <div class="change-password-form-container">
            {{ form_start(form, {'method': 'POST', 'attr': {'class': 'change-password-form'}}) }}

                <div class="form-header">
                    <h1>zmień hasło</h1>
                </div>

                {% if msg is defined %}
                    {% if errno is defined %}
                        <p class="form-message-error">{{ msg }}</p>
                    {% else %}
                        <p class="form-message-success">{{ msg }}</p>
                    {% endif %}
                {% endif %}

                <div class="old-password-container">
                    <p>Stare hasło</p>
                    {{ form_widget(form.old_password, {'attr': {'placeholder': 'Stare hasło'}}) }}
                </div>

                <div class="new-password-container">
                    <p>Nowe hasło</p>
                    {{ form_widget(form.new_password, {'attr': {'placeholder': 'Nowe hasło'}}) }}
                </div>

                <div class="repeat-password-container">
                    <p>Powtórz hasło</p>
                    {{ form_widget(form.repeated_password, {'attr': {'placeholder': 'Powtórz hasło'}}) }}
                </div>

                <div class="button-container">
                    {{ form_widget(form.change, {'attr': {'class': 'change-password-button'}, 'label': 'Zmień hasło'}) }}
                </div>

                {{ form_widget(form._token) }}

            {{ form_end(form, {'render_rest': false})}}
        </div>
    </div>
</body>

templates/header_nav.html.twig
<header>
    <h1>twarzobaza</h1>
</header>
<nav>
    <ul>
        <li>
            <i class="fas fa-home"></i>
            <a href="{{ path('home') }}">strona główna</a>
        </li>
        <li>
            <i class="fas fa-user"></i>
            <a href="{{ path('user') }}">konto użytkownika</a>
        </li>
        <li>
            <i class="fas fa-search"></i>
            <a href="{{ path('search') }}">wyszukaj w bazie</a>
        </li>
        <li>
            <i class="fas fa-chart-bar"></i>
            <a href="{{ path('statistics') }}">statystyki</a>
        </li>
        <li>
            <i class="fas fa-sign-out-alt"></i>
            <a href="{{ path('app_logout') }}">wyloguj</a>
        </li>
    </ul>
</nav>

templates/home.html.twig
<!DOCTYPE html>
<head>
    <link rel="stylesheet" type="text/css" href="{{ asset('css/header-nav-style.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('css/home-style.css') }}">
    <script src="{{ asset('https://kit.fontawesome.com/3d9e005fd2.js') }}" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{{ asset('js/home.js') }}" defer></script>
    <title>Twarzobaza</title>
</head>
<body>
    <div class="main-container">
        {{ include('header_nav.html.twig') }}
        <main>
            <h1>Witaj!</h1>
            <p>Data aktualnej bazy: 20.02.2021</p>
            <hr>
            {% if is_granted('ROLE_FULL') %}
                <a class="add-post" href="{{ path('app_addpost') }}">DODAJ POST</a>
            {% endif %}

            {% for post in posts %}
                <div class="post">
                    <h1> {{ post.title }} </h1>

                    <p>
                        {{ post.content|slice(0, 500) }}
                        {% if post.content|length > 500 %}
                            <span>(...)</span>
                        {% endif %}
                    </p>

                    <div class="post-bottom">
                        <div class="date-author">
                            <span class="author"><b>Autor: </b>{{ post.author.name }}</span>
                            <span class="date"><b>Data dodania: </b>{{ post.date|date("Y-m-d H:i:s") }}</span>
                        </div>
                        <a href="post/{{post.id}}" class="see-post">Zobacz post</a>
                        {% if app.user.id == post.author.id %}
                            <span class="remove">Usuń</span>
                        {% endif %}
                    </div>
                    <input class="postid" type="hidden" value="{{ post.id }}">
                </div>
            {% endfor %}
        </main>
    </div>
</body>

templates/login.html.twig
<!-- <?php session_start(); ?> -->

<!DOCTYPE html>
<head>
    <link rel="stylesheet" type="text/css" href="{{ asset('css/header-nav-style.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('css/login-style.css') }}"> 
    <title>Twarzobaza</title>
</head>
<body>
    <div class="main-container">
        <header>
            <h1>twarzobaza</h1>
        </header>
        <div class="login-form-container">
            <form class="login-form" action="login" method="POST">
                <div class="form-header">
                    <h1>logowanie</h1>
                </div>
                <!-- <?php if (isset($message)): ?>
                <p class="login-form-message"><?= $message ?></p>
                <?php endif; ?> -->
                <div class="login-container">
                    <p>Login</p>
                    <input name="login" type="text" placeholder="Login">
                </div>
                <div class="password-container">
                    <p>Hasło</p>
                    <input name="password" type="password" placeholder="Hasło">
                </div>
                <div class="button-container">
                    <button class="login-button" type="submit">zaloguj</button>
                </div>
            </form>
        </div>
    </div>
</body>

templates/post.html.twig
<!DOCTYPE html>
<head>
    <link rel="stylesheet" type="text/css" href="{{ asset('css/header-nav-style.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('css/post-style.css') }}">
    <script src="{{ asset('https://kit.fontawesome.com/3d9e005fd2.js') }}" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{{ asset('js/post.js') }}" defer></script>
    <title>Twarzobaza</title>
</head>
<body>
    <div class="main-container">
        {{ include('header_nav.html.twig') }}
        <main>
            <div class="post">
                <h1 class="post-title"> {{ post.title }} </h1>
                <p class="post-content"> {{ post.content }} </p>
                <div class="post-bottom">
                    <div class="date-author">
                        <span class="author"><b>Autor: </b>{{ post.author.name }}</span>
                        <span class="date"><b>Data dodania: </b>{{ post.date|date("Y-m-d H:i:s") }}</span>
                    </div>
                    {% if app.user.id == post.author.id %}
                        <span class="edit">Edytuj</span>
                        <span class="confirm">Zatwierdź</span>
                        <span class="undo">Cofnij</span>
                        <a class="remove" href="{{ path('removepost', {'id': post.id}) }}">Usuń</a>
                    {% endif %}
                </div>
                <input class="postid" type="hidden" value="{{ post.id }}">
            </div>
        </main>
    </div>
</body>

templates/search.html.twig
<!DOCTYPE html>
<head>
    <link rel="stylesheet" type="text/css" href="{{ asset('css/header-nav-style.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('/css/search-style.css') }}">
    <script src="{{ asset('https://kit.fontawesome.com/3d9e005fd2.js') }}" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{{ asset('js/search.js') }}" defer></script>
    <script type="text/javascript" src="{{ asset('js/search-validation.js') }}" defer></script> 
    <title>Twarzobaza</title>
</head>
<body>
    <div class="main-container">
        {{ include("header_nav.html.twig") }}
        <main>
            <section class="search-form-container">
                {{ form_start(form, {'attr': {'class': 'search-form'}}) }}
                    <label for="user">Użytkownik</label>
                    {{ form_widget(form.user) }}
                    <p class="date-input-text">Data (format RRRR-MM-DD GG:MM:SS)</p>
                    {{ form_widget(form.start_date) }}
                    {{ form_widget(form.end_date) }}
                    <p class="search-input-text">Szukana fraza</p>
                    <div class="search-input-container">
                        {{ form_widget(form.search_input) }}
                        {{ form_widget(form.search, {'attr': {'class': 'fas fa-search'}, 'value': ''}) }}
                    </div>
                    {{ form_widget(form._token) }}
                {{ form_end(form, {'render_rest': false}) }}
                {# {{ form(form) }} #}
            </section> 
            
            <section class="results-container">
                <h1></h1>
                <div class="results-table-container">
                    <table>
                    </table>
                </div>
                <div class="pagination">
                    <span id="previous">&#60;</span>
                    <span id="current-page"></span>
                    <span>z</span>
                    <span id="last-page">5</span>
                    <span id="next">&#62;</span>
                </div>
            </section>
            <br><br>
        </main>
    </div>
</body>

<template id="table-header-template">
    <tr>
        <th>Użytkownik</th>
        <th>Data</th>
        <th>Treść wiadomości</th>
    </tr>
</template>

<template id="message-template">
    <tr>
        <td>Użytkownik</td>
        <td>Data</td>
        <td>Treść wiadomości</td>
    </tr>
</template>

<template id="pagination-template">
        
</template>

templates/statistics.html.twig
<!DOCTYPE html>
<head>
    <link rel="stylesheet" type="text/css" href="{{ asset('css/header-nav-style.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('css/statistics-style.css') }}">
    <script type="text/javascript" src="{{ asset('js/statistics.js') }}" defer></script>
    <script src="{{ asset('https://kit.fontawesome.com/3d9e005fd2.js') }}" crossorigin="anonymous"></script>
    <title>Twarzobaza</title>
</head>
<body>
    <div class="main-container">
        {{ include("header_nav.html.twig") }}
        <main>
            <section class="statistics-form-container">
                {{ form_start(form, {'attr': {'class': 'statistics-form'}}) }}
                    <label for="user">Użytkownik</label>
                    {{ form_widget(form.user) }}
                    <label for="groupby">Grupuj według</label>
                    {{ form_widget(form.groupby) }}
                    {{ form_widget(form.generate, {'attr': {'class': 'fas fa-arrow-right'}, 'value': ''}) }}
                {{ form_end(form, {'render_rest': false}) }}
            </section>
            <section class="results-container">
                <h1></h1> 
                <div class="results-table-container">
                     <table>
                    </table>
                </div>
            </section>
            <br><br>
        </main>
    </div>
</body> 

templates/user.html.twig
<!DOCTYPE html>
<head>
    <link rel="stylesheet" type="text/css" href="{{ asset('css/user-style.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('css/header-nav-style.css') }}">
    <script src="{{ asset('https://kit.fontawesome.com/3d9e005fd2.js') }}" crossorigin="anonymous"></script>
    <title>Twarzobaza</title>
</head>
<body>
    <div class="main-container">
        {{ include('header_nav.html.twig') }}
        <main>
           <section class="user-info-container">
               <div class="user-info">
                    <h1> {{ user.name }} </h1>
                    <p>Dołączył: {{ user.joinDate|date('Y-m-d') }} </p>
                    {% if is_granted('ROLE_FULL') %}
                        <p>Pełne uprawnienia</p>
                    {% else %}
                        <p>Częściowe uprawnienia</p>
                    {% endif %}
                    <p>Konta: 
                        {% set str = "" %}
                        {% for account in accounts %}
                            {% set str = str ~ account.name ~ " (ID " ~ account.id ~ "), " %}
                        {% endfor %}
                        {{ str|trim(", ") }}
                    </p>
                    <a href="change_password">Zmień hasło</a>
               </div>
               <div class="user-image">
                   <img src="{{ asset('img/' ~ user.username ~ '.jpg') }}">
               </div>
           </section>
        </main>
    </div>
</body>